<?php

declare(strict_types=1);

/**
 * Middleware that redirects the Whups home route to the user's preferred
 * default view.
 *
 * Maps the `whups_default_view` preference value to a named route and
 * issues a redirect to the URL generated by the routes mapper.
 *
 * Copyright 2026 The Horde Project (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (BSD). If you
 * did not receive this file, see http://www.horde.org/licenses/bsdl.php.
 */

namespace Horde\Whups\Middleware;

use Horde\Routes\Mapper;
use Horde_Prefs;
use Psr\Http\Message\ResponseFactoryInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

class DefaultViewRedirect implements MiddlewareInterface
{
    /**
     * Map preference values to route names.
     */
    private const PREF_TO_ROUTE = [
        'mybugs'        => 'MyBugs',
        'search'        => 'Search',
        'ticket/create' => 'TicketCreate',
    ];

    private const FALLBACK_ROUTE = 'MyBugs';

    public function __construct(
        private readonly Horde_Prefs $prefs,
        private readonly Mapper $mapper,
        private readonly ResponseFactoryInterface $responseFactory,
    ) {}

    public function process(
        ServerRequestInterface $request,
        RequestHandlerInterface $handler,
    ): ResponseInterface {
        $prefValue = $this->prefs->getValue('whups_default_view');
        $routeName = self::PREF_TO_ROUTE[$prefValue] ?? self::FALLBACK_ROUTE;
        $url = $this->mapper->utils->urlFor($routeName);

        return $this->responseFactory
            ->createResponse(302)
            ->withHeader('Location', $url);
    }
}
