<?php

/**
 * MIME Viewer configuration for Whups.
 *
 * Settings in this file override settings in horde/config/mime_drivers.php.
 * All drivers configured in that file, but not configured here, will also
 * be used to display MIME content.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE!
 * Local overrides MUST be placed in var/config/whups/mime_drivers.local.php or
 * var/config/whups/mime_drivers.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use var/config/whups/mime_drivers-servername.php.
 */

$mime_drivers = [
    /* Zip File archive viewer. */
    'zip' => [
        'handles' => [
            'application/x-compressed',
            'application/x-zip-compressed',
            'application/zip',
            'x-extension/zip',
        ],
        'icons' => [
            'default' => 'compressed.png',
        ],
    ],
];
