<?php

// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/whups/routes.local.php and run composer horde:reconfigure

namespace Horde\Whups;

use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

// Fat middleware stack for routes that need full Horde framework + auth
$fatStack = [
    \Horde\Core\Middleware\LeanErrorHandler::class,
    \Horde\Core\Middleware\InitHordeFramework::class,
    \Horde\Core\Middleware\AppBootstrap::class,
    \Horde\Core\Middleware\ErrorFilter::class,
    \Horde\Core\Middleware\AuthHordeSession::class,
    \Horde\Core\Middleware\RedirectToLogin::class,
];

// Webhook receiver for Github
$mapper->connect(
    'GithubWebhook',
    '/webhook/github',
    [
        'controller' => Webhook\Github::class,
        'HordeAuthType' => 'NONE',
    ]
);

// Home / default view — redirects to user's preferred view
$mapper->buildRoute(uri: '/', name: 'WhupsHome')
    ->withController(Middleware\DefaultViewRedirect::class)
    ->withDefaults(['action' => 'index'])
    ->withMiddleware([
        \Horde\Core\Middleware\LeanErrorHandler::class,
        \Horde\Core\Middleware\InitHordeFramework::class,
        \Horde\Core\Middleware\AppBootstrap::class,
        \Horde\Core\Middleware\AuthHordeSession::class,
        \Horde\Core\Middleware\RedirectToLogin::class,
    ])
    ->withSecondaryRoute('/index.php')
    ->add();

// --- Ticket routes ---

// Ticket view: /ticket/:id
$mapper->buildRoute(uri: '/ticket/:id', name: 'TicketView')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'view'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/index.php')
    ->add();

// Ticket create: /ticket/create
$mapper->buildRoute(uri: '/ticket/create', name: 'TicketCreate')
    ->withController(Controller\Ticket\CreateController::class)
    ->withDefaults(['action' => 'create'])
    ->withMiddleware([
        \Horde\Core\Middleware\LeanErrorHandler::class,
        \Horde\Core\Middleware\InitHordeFramework::class,
        \Horde\Core\Middleware\AppBootstrap::class,
        \Horde\Core\Middleware\ErrorFilter::class,
        \Horde\Core\Middleware\AuthHordeSession::class,
        \Horde\Core\Middleware\RedirectToLogin::class,
    ])
    ->withSecondaryRoute('/ticket/create.php')
    ->add();

// Ticket RSS: /ticket/:id/rss
$mapper->buildRoute(uri: '/ticket/:id/rss', name: 'TicketRss')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'rss'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/rss.php')
    ->add();

// Ticket delete-attachment: /ticket/:id/delete-attachment
$mapper->buildRoute(uri: '/ticket/:id/delete-attachment', name: 'TicketDeleteAttachment')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'delete_attachment'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/delete_attachment.php')
    ->add();

// Ticket delete-history: /ticket/:id/delete-history
$mapper->buildRoute(uri: '/ticket/:id/delete-history', name: 'TicketDeleteHistory')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'delete_history'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/delete_history.php')
    ->add();

// Ticket delete-multiple: /ticket/delete-multiple
$mapper->buildRoute(uri: '/ticket/delete-multiple', name: 'TicketDeleteMultiple')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'delete_multiple'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/delete_multiple.php')
    ->add();

// Ticket actions: /ticket/:id/:action (update, comment, watch, delete, queue, type, attachments)
$mapper->buildRoute(uri: '/ticket/:id/:action', name: 'TicketAction')
    ->withController(Ui\WhupsUi::class)
    ->withRequirements(['id' => '\d+', 'action' => 'update|comment|watch|delete|queue|type|attachments'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/:action.php')
    ->add();

// --- Queue routes ---

// Queue view: /queue/:slug
$mapper->buildRoute(uri: '/queue/:slug', name: 'QueueView')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'view'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/queue/index.php')
    ->add();

// Queue RSS: /queue/:slug/rss
$mapper->buildRoute(uri: '/queue/:slug/rss', name: 'QueueRss')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'rss'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/queue/rss.php')
    ->add();

// --- Query routes ---

// Query builder: /query/builder (must be before /query/:slug)
$mapper->buildRoute(uri: '/query/builder', name: 'QueryBuilder')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'builder'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/query/index.php')
    ->add();

// Query run: /query/:slug
$mapper->buildRoute(uri: '/query/:slug', name: 'QueryRun')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'run'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/query/run.php')
    ->add();

// Query RSS: /query/:slug/rss
$mapper->buildRoute(uri: '/query/:slug/rss', name: 'QueryRss')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'rss'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/query/rss.php')
    ->add();

// --- Other routes ---

// Search
$mapper->buildRoute(uri: '/search', name: 'Search')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'search'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/search.php')
    ->add();

// Search RSS
$mapper->buildRoute(uri: '/search/rss', name: 'SearchRss')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'rss'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/search/rss.php')
    ->add();

// My Bugs
$mapper->buildRoute(uri: '/mybugs', name: 'MyBugs')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'mybugs'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/mybugs.php')
    ->add();

// My Bugs edit
$mapper->buildRoute(uri: '/mybugs/edit', name: 'MyBugsEdit')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'mybugs_edit'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/mybugs_edit.php')
    ->add();

// Reports
$mapper->buildRoute(uri: '/reports', name: 'Reports')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'reports'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/reports.php')
    ->add();

// Admin
$mapper->buildRoute(uri: '/admin', name: 'Admin')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'admin'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/admin/index.php')
    ->add();
