<?php

// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/whups/routes.local.php and run composer horde:reconfigure

namespace Horde\Whups;

use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

// Fat middleware stack for routes that need full Horde framework + auth
$fatStack = [
    // \Horde\Core\Middleware\RampageLogError::class,
//    \Horde\Core\Middleware\InitHordeFramework::class,
//    \Horde\Core\Middleware\AppBootstrap::class,
    \Horde\Core\Middleware\ErrorFilter::class,
    \Horde\Core\Middleware\AuthHordeSession::class,
    \Horde\Core\Middleware\RedirectToLogin::class,
];

// Webhook receiver for Github
$mapper->connect(
    'GithubWebhook',
    '/webhook/github',
    [
        'controller' => Webhook\Github::class,
        'HordeAuthType' => 'NONE',
    ]
);

// Home / default view — redirects to user's preferred view
$mapper->buildRoute(uri: '/', name: 'WhupsHome')
    ->withController(Middleware\DefaultViewRedirect::class)
    ->withDefaults(['action' => 'index'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/index.php')
    ->add();

// --- Ticket routes ---

// Ticket view: /ticket/:id
$mapper->buildRoute(uri: '/ticket/:id', name: 'TicketView')
    ->withController(Controller\Ticket\ViewController::class)
    ->withDefaults(['action' => 'view'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/index.php')
    ->add();

// Ticket create: /ticket/create
$mapper->buildRoute(uri: '/ticket/create', name: 'TicketCreate')
    ->withController(Controller\Ticket\CreateController::class)
    ->withDefaults(['action' => 'create'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/create.php')
    ->add();

// Ticket RSS: /ticket/:id/rss
$mapper->buildRoute(uri: '/ticket/:id/rss', name: 'TicketRss')
    ->withController(Controller\Ticket\RssController::class)
    ->withDefaults(['action' => 'rss'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/rss.php')
    ->add();

// Ticket delete-attachment: /ticket/:id/delete-attachment
$mapper->buildRoute(uri: '/ticket/:id/delete-attachment', name: 'TicketDeleteAttachment')
    ->withController(Controller\Ticket\DeleteAttachmentController::class)
    ->withDefaults(['action' => 'delete_attachment'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/delete_attachment.php')
    ->add();

// Ticket delete-history: /ticket/:id/delete-history
$mapper->buildRoute(uri: '/ticket/:id/delete-history', name: 'TicketDeleteHistory')
    ->withController(Controller\Ticket\DeleteHistoryController::class)
    ->withDefaults(['action' => 'delete_history'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/delete_history.php')
    ->add();

// Ticket delete-multiple: /ticket/delete-multiple
$mapper->buildRoute(uri: '/ticket/delete-multiple', name: 'TicketDeleteMultiple')
    ->withController(Controller\Ticket\DeleteMultipleController::class)
    ->withDefaults(['action' => 'delete_multiple'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/delete_multiple.php')
    ->add();

// Ticket delete: /ticket/:id/delete
$mapper->buildRoute(uri: '/ticket/:id/delete', name: 'TicketDelete')
    ->withController(Controller\Ticket\DeleteController::class)
    ->withDefaults(['action' => 'delete'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/delete.php')
    ->add();

// Ticket watch: /ticket/:id/watch
$mapper->buildRoute(uri: '/ticket/:id/watch', name: 'TicketWatch')
    ->withController(Controller\Ticket\WatchController::class)
    ->withDefaults(['action' => 'watch'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/watch.php')
    ->add();

// Ticket attachments: /ticket/:id/attachments
$mapper->buildRoute(uri: '/ticket/:id/attachments', name: 'TicketAttachments')
    ->withController(Controller\Ticket\AttachmentsController::class)
    ->withDefaults(['action' => 'attachments'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/attachments.php')
    ->add();

// Ticket comment: /ticket/:id/comment
$mapper->buildRoute(uri: '/ticket/:id/comment', name: 'TicketComment')
    ->withController(Controller\Ticket\CommentController::class)
    ->withDefaults(['action' => 'comment'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/comment.php')
    ->add();

// Ticket update: /ticket/:id/update
$mapper->buildRoute(uri: '/ticket/:id/update', name: 'TicketUpdate')
    ->withController(Controller\Ticket\UpdateController::class)
    ->withDefaults(['action' => 'update'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/update.php')
    ->add();

// Ticket set-queue: /ticket/:id/queue
$mapper->buildRoute(uri: '/ticket/:id/queue', name: 'TicketQueue')
    ->withController(Controller\Ticket\QueueMoveController::class)
    ->withDefaults(['action' => 'queue'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/queue.php')
    ->add();

// Ticket set-type: /ticket/:id/type
$mapper->buildRoute(uri: '/ticket/:id/type', name: 'TicketType')
    ->withController(Controller\Ticket\TypeChangeController::class)
    ->withDefaults(['action' => 'type'])
    ->withRequirements(['id' => '\d+'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/ticket/type.php')
    ->add();

// --- Queue routes ---

// Queue view: /queue/:slug
$mapper->buildRoute(uri: '/queue/:slug', name: 'QueueView')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'view'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/queue/index.php')
    ->add();

// Queue RSS: /queue/:slug/rss
$mapper->buildRoute(uri: '/queue/:slug/rss', name: 'QueueRss')
    ->withController(Controller\Rss\QueueRssController::class)
    ->withDefaults(['action' => 'rss'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/queue/rss.php')
    ->add();

// --- Query routes ---

// Query builder: /query/builder (must be before /query/:slug)
$mapper->buildRoute(uri: '/query/builder', name: 'QueryBuilder')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'builder'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/query/index.php')
    ->add();

// Query run: /query/:slug
$mapper->buildRoute(uri: '/query/:slug', name: 'QueryRun')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'run'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/query/run.php')
    ->add();

// Query RSS: /query/:slug/rss
$mapper->buildRoute(uri: '/query/:slug/rss', name: 'QueryRss')
    ->withController(Controller\Rss\QueryRssController::class)
    ->withDefaults(['action' => 'rss'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/query/rss.php')
    ->add();

// --- Other routes ---

// Search
$mapper->buildRoute(uri: '/search', name: 'Search')
    ->withController(Controller\SearchController::class)
    ->withDefaults(['action' => 'search'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/search.php')
    ->add();

// Search RSS
$mapper->buildRoute(uri: '/search/rss', name: 'SearchRss')
    ->withController(Controller\Rss\SearchRssController::class)
    ->withDefaults(['action' => 'rss'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/search/rss.php')
    ->add();

// My Bugs
$mapper->buildRoute(uri: '/mybugs', name: 'MyBugs')
    ->withController(Controller\MyBugsController::class)
    ->withDefaults(['action' => 'mybugs'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/mybugs.php')
    ->add();

// My Bugs edit
$mapper->buildRoute(uri: '/mybugs/edit', name: 'MyBugsEdit')
    ->withController(Controller\MyBugsEditController::class)
    ->withDefaults(['action' => 'mybugs_edit'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/mybugs_edit.php')
    ->add();

// Reports
$mapper->buildRoute(uri: '/reports', name: 'Reports')
    ->withController(Controller\ReportsController::class)
    ->withDefaults(['action' => 'reports'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/reports.php')
    ->add();

// Admin
$mapper->buildRoute(uri: '/admin', name: 'Admin')
    ->withController(Ui\WhupsUi::class)
    ->withDefaults(['action' => 'admin'])
    ->withMiddleware($fatStack)
    ->withSecondaryRoute('/admin/index.php')
    ->add();

// Lean bootstrap test — bisecting middleware stack
$mapper->buildRoute(uri: '/lean-test', name: 'LeanTest')
    ->withController(Controller\LeanTestController::class)
    ->withMiddleware($fatStack)
    ->add();
