<?php
// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/whups/routes.local.php and run composer horde:reconfigure
namespace Horde\Whups;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

// Webhook receiver for Github
$mapper->connect(
    'GithubWebhook',
    '/webhook/github',
    [
        'controller' => Webhook\Github::class,
        // The webhook is not protected at this level but you can configure a secret in conf.php
        'HordeAuthType' => 'NONE',
    ]
);
$mapper->connect(
    'WhupsHomeIndex',
    '/index.php',
    [
        'controller' => Ui\WhupsUi::class,
        // The webhook is not protected at this level but you can configure a secret in conf.php
        'HordeAuthType' => 'NONE',
    ]
);
$mapper->connect(
    'WhupsHome',
    '/',
    [
        'controller' => Ui\WhupsUi::class,
        // The webhook is not protected at this level but you can configure a secret in conf.php
        'HordeAuthType' => 'NONE',
    ]
);
