<?php

/**
 * This file defines the templates used in various parts of Whups.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE!
 * Local overrides MUST be placed in var/config/whups/templates.local.php or
 * var/config/whups/templates.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use var/config/whups/templates-servername.php.
 *
 * Hopefully this will all migrate to a database in the future, but
 * for now, this is it.
 *
 * More docs coming as this gets fleshed out and used more.
 */

$_templates['html-simple'] = [
    'type' => 'searchresults',
    'filename' => 'report.html',
    'name' => _("Simple HTML Report"),
    'sortby' => ['type_name', 'timestamp'],
    'sortdir' => [0, 1],
    'view_template' => 'html-simple',
];

$_templates['csv'] = [
    'type' => 'searchresults',
    'name' => _("Comma Separated Values (CSV file)"),
    'filename' => 'report.csv',
    'callback' => '_csvQuote',
    'view_template' => 'csv',
];

if (!function_exists('_csvQuote')) {
    function _csvQuote($data, $key)
    {
        if (strpos($data, ',') !== false) {
            $data = '"' . str_replace('"', '\"', $data) . '"';
        }
    }
}
